### ISSUE TITLE
Point size in "Selected Data" should the same as in "Selected Pen Points" in "Spatial View"

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#119]
At the moment it is not possible to alter the point size in "Selected Data". This is not necessarily an issue for the settings window, if they just get the same point size and colour as in "Selected Pen Points" in "Spatial View".

**Comment by isolver** [comment]
This was done intentionally by me; thinking that in the selected data
window you would want to see what points are pressed vs hover. If it used
the selected data 'pen' from the spatial view, this would get lost since
all selected points in the spatial view use the same graphic.

Does this make sense?

**Comment by isolver** [comment]
Also renamed "Selected Data" gui tab to "Selected Pen Points" .

**Comment by isolver** [comment]
Fixed when issue #123 was fixed.
