### ISSUE TITLE
Spatial view: selecting samples loses hover / press distinction

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#122]
In the spatial view it's clear which samples are pressed and which are hover _until_ you select them. Then they both look that same. This makes setting selection boundaries difficult (sometimes impossible).

Need to make selected hover samples paler / smaller (i.e. maintain the visual distinction that is present when no selected)

**Comment by isolver** [comment]
On Fri, Jan 1, 2016 at 6:45 AM, Mark Torrance notifications@github.com
wrote:

> then they both look that same.

I agree that it would be nice from a usability POV to be able to see the
pressed stated for selected samples by only looking at the spatial view
tab.

The app's current functionality stems from the spatial view only using one
qt 'pen' and 'brush' to draw all selected samples. Pressed state is not
taken into account for selected samples in this view. This makes updating
the selected samples in the view faster, since an array of qt pen and brush
objects (array length == selected sample count) is not needed and does not
need to be updated for each selection change.

Maybe the reason why the current functionality was acceptable before was
because the timeline view can be used to see which of the selected samples
are pressed or not. A downside here is this means having to look back and
forth between the timeline and spatial views to tweak the selected samples
though. I imagine that this maybe needed regardless, since it is the
timeline view that is used to change the selection region / samples.

**Comment by Mark-Torrance** [comment]
The reason that this wasn't an issue before was that we didn't have data that contained hover (zero pressure) samples. Doing markup with the quick keys for linguistic units (letters / words / sentences) is very quick indeed. You don't have to look at the timeline at all, and doing so would slow things down substantially (maybe by x2 or more). The only issue is that the trace in the spatial view becomes ambiguous when selected, but this really is quite a big issue. I found that I have to look at the hard copy of my trace (I was using an inking stylus on paper overlaid on the tablet) to work out what I'd actually written.

Is there no way we can make this distinction without seriously slowing the program down?

**Comment by isolver** [comment]
I will make the change and we can see if the difference in overhead is
noticeable. Frankly, there are other areas in the code that probably
contribute to a lot to the current app. performance. I had hoped to address
some of this in this round of code changes, but it will likely need to be
deferred until some future time.

**Comment by Mark-Torrance** [comment]
I've just tried selecting actions with two of the cores on my laptop tuned off (I think that's what power saver currently does - it normally gives noticeably poorer performance) - lag is tiny and not a all problematic as things stand.

**Comment by isolver** [comment]
fixed. I use the same color transform for selected data with 0 pressure as is done for unselected data; the selected data color is made darker for unselected data.
