### ISSUE TITLE
Selected data view: visually distinguish press and hover samples

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#123]
What it says. Same reasons as #122 but lower priority.

**Comment by isolver** [comment]
My initial thought is that this maybe the same or even higher priority than  #122 since the only samples seen in the selected sample view are, well, the selected samples. 

This may also be complete rubbish on my part; the opinion of researchers using the tool is much more likely to be valid than my own imagined use cases. ;)

**Comment by Mark-Torrance** [comment]
It's less of an issue only because this view is less important generally for markup - though it is useful for looking at the detail of segments. For markup above the stroke level and when the focus is on what's written (which will normally be the case) rather than in-air pen movements, it really is the spatial view that is that main focus.

**Comment by isolver** [comment]
fixed. I use the same color transform for selected data with 0 pressure as is done for unselected data; the selected data color is made darker for unselected data.

Also, the drawing color used in the selected data view now matches the selected data color used in the spatial view. It therefore changes based on whether selected data is valid for segment creation or not.
