### ISSUE TITLE
txyp files not plotting correctly in spatial view

### ISSUE THREAD

**Issue by isolver** [isolver/OpenHandWrite#141]
~~Note from Sol, this maybe an issue with plotting pen stroke boundary points in all views, need to check....~~

From @Mark-Torrance :

txyp files not plotting correctly in spatial view. Initially I thought this might just be messy data but (a) these are files I've looked at before and they didn't appear this way, and (b) timeline and spatial view seem to give different locations. See second image.

![capture](https://cloud.githubusercontent.com/assets/3226576/12628482/4aba825e-c53b-11e5-9e69-cd493f7317b6.PNG)

![capture](https://cloud.githubusercontent.com/assets/3226576/12628432/0d944202-c53b-11e5-9ba8-e7d97bbe9189.PNG)

**Comment by isolver** [comment]
This seems to be resulting from a negative side effect on data filtering caused by changing the txyp and xml files to not find sample Series based on ISI. Now these files just have one Series that spans the whole data file.

This is important because MarkWrite filters data at a Series by Series level. i.e. each sample Series is filtered independently. Series level filtering is needed so that the filtered values of samples near the end of Series N are not invalidly being biased by samples near the beginning of Series N+1 and visa versa.  This issue is what we are seeing now in the plotted filtered data for txyp and xml files, but not hdf5 files. 

I wish I had thought of this issue when we were discussing whether to drop Series level parsing from non hdf5 files or not. The only way I see fixing this issue is to add back Series level parsing based on an ISI value that is determined by default using the ISI distribution of the data, while also allowing a user to override the default value and manually set a threshold.

@Mark-Torrance and @g-no, let me know if you see another way to apply proper filtering to the pen data without doing it on a Series by Series level.

**Comment by isolver** [comment]
I have added a "Filter Imported Pen Data" app setting to MarkWrite so you can see the effect I am referring to. Default is True, so to see unfiltered data, change it to false and reload the data file.

You can downloaded the latest markwrite source directory directly from github if you want to try it out:
1. [Download a zip of the OpenHandWrite project source](https://github.com/isolver/OpenHandWrite/archive/master.zip). 
2. Replace your existing OpenHandWrite/markwrite folder with the OpenHandWrite-master/markwrite folder in the downloaded zip.  

This does not solve the root problem IMO, but may make it easier to see what I am talking about. Users may also like the option in general I guess?

**Comment by Mark-Torrance** [comment]
Ah, now you see I should have been paying attention in all of the discussion about filtering. I don't actually know what "filtering" means here.

But.. If the issue is just that filtering needs to make use of local averages (or minima and maxima), then why not do this on the basis of run rather than series? This is now independent of both report output and segment selection actions, because these are both handled by the Status variable. So you can quantize the data how you like? Or am I missing something?

I've used the new code to look at the unfiltered data. Just visually, unfiltered txyp files look absolutely fine to me. For the letter / word / sentence level analyses that researchers who have collected these data are likely to want, I am not sure what filtering achieves. But then I don't know what filtering is :)

**Comment by isolver** [comment]
> why not do this on the basis of run rather than series? ..... So you can
> quantize the samples how you like? Or am I missing something?

Filtering on a per run basis when Series are not present is an option, but
I am not sure if it is a good idea. ;)

The number of points in a Run in the xml and txyp files is often small
relative to the filter window size. Markwrite uses a window size of 13.
There is often little benefit in filtering arrays with a length that is
less than 2 - 3 times the window size used by the filter: I assume this
also applies to the case of short sample runs. Furthermore, windowssize/2
samples at the start and end of each array can not really be filtered and
are instead left as is, or interpolated based on adjacent data to try and
minimize any discontinuity that could be caused in these areas of the data.

Guido wanted filters to be applied at a Series level; I assume because of
the above reasons. Probably he also thought that using series would mean
better filtering at the start and end of runs because the adjacent hover
data is factored in, which makes sense. He could give better input on this
of course.

In the xml and txyp files, we do not have hover data, so I agree that some
if the benefit of series level filtering is lost. However in many cases the
runs that can be grouped into series based on a relatively high Isi
value would be better filtered when grouped together compared to separately.

> ....the basis of run rather than series? This is now independent of both
> report output and segment selection actions, because these are both handled
> the Status variable.

I guess I also still do not understand what the negative is for having
the ISI based series parsing when series markers can not be provided in the
sample status for the given source file type (xml and txyp). My thinking:
- Worst case, the series level grouping can just be ignored by the user.
- there are benefits in having ISI based series parsing vs. no series
  detection at all:
  - as we have already seen, filtering of the data benefits from having
    the file parsed into sample series, even in cases where there is
    not hover
    data between temporally close runs.
  - from a data selection usability POV, allowing data selection
    movement at a series level seems to be useful. Given an appropriate ISI
    threshold, so the series parsed are sensible for the most part,
    being able
    to jump from an approximate word to word level is useful sometimes.
  - At minimum, using a high valued ISI for series parsing will in many
    cases at least help do a rough trial level grouping of samples. Again,
    likely useful from a gui data selection / navigation usability POV.

**Comment by Mark-Torrance** [comment]
Thanks for reminder about filtering. I remember now (and chatted with Guido about it before we started this project).

> I guess I also still do not understand what the negative is for having the ISI based series parsing when series markers can not be provided in the sample status for the given source file type (xml and txyp). 

Two overlapping responses. In summary "we don't need them" and "we can't get them". But I really might be missing something, so do tell me if I'm wrong.
1. Filtering provides better estimates of sample x,y, right? If so, I think the answer to this is simply that for people who have collected data with eye and pen or with handspy, this is total-non issue. Handspy and eye and pen users (including me) are not concerned with precise shape and velocity of strokes. If we were, we'd use Ductus. As long as we can read the text, that's fine. These existing users will now either move over to GetWrite (if they are at all concerned with timing accuracy and / or location accuracy) or they will remain unconcerned and continue with what they know. No one is going to gain from filtering E&P or HandSpy data.
2. Unless I'm missing something, we just don't have series data from E&P or HandSpy (xml). Sampling terminates as soon as pressure = 0. We simply can't tell what part of the next period was hover and what part was out-of-range. In the txyp data file there are long ISIs but these are always within run. Assuming that it's very difficult to go from press to out-of-range in less than 8 ms, these mid-run long ISIs are more or less never going to be genuine series terminators (and you can tell by where they occur that this they aren't). They have occured because of Windows events, or something.

**Comment by isolver** [comment]
I'll leave the debate where it stands now and go with your judgement call on this. It is usually better than mine anyhow. ;)

So the question is: given we know what is causing the issue, but can not fix the root issue, what should we do?
1. Make Filter Data setting False by default. If a user sets it to true and loads xml or txyp file, suffer the consequences.
2. Change app settings: have 3 settings for filtering loaded data, one setting for each file type
3. Only ever allow filtering of hdf5 based data.
4. ???

**Comment by Mark-Torrance** [comment]
Ah, I'm torn between 1 and 3. I'm a bit concerned about using file type as the critical criterion. You could have hdf5 files that don't have good status data (in principle).

So, it's an informed user decision. So 1 is the right way to go.

**Comment by isolver** [comment]
Fixed. Only thing that has changed in mw app is that the Filter Imported Pen Data setting now defaults to False
