### ISSUE TITLE
import/export for settings

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#185]
It would be good to have an import/export for the settings in MarkWrite.
BTW: Is it correct, that the settings are already saved in mwp-files?

**Comment by isolver** [comment]
@g-no:
> BTW: Is it correct, that the settings are already saved in mwp-files?

There are project level settings and application level settings:

1. Project settings are saved in the .wmp file along with the project data etc. Project level settings mainly include info on the different project gui views and selected stroke etc so that next time a project is opened these are remembered.

2. Application level settings are saved in a usersettings.pkl file. These are the settings you see when you open the Project settings Dialog, and act as the default settings for new projects / data imports.  It also includes the settings dialog size now.

So you would like to be able to save a usersettings.pkl file as a different name and also restore settings from a saved file the user selects?

**Comment by g-no** [comment]
> So you would like to be able to save a usersettings.pkl file as a different name and also restore settings from a saved file the user selects?

Yes, that's it.

**Comment by isolver** [comment]
Implemented project Settings Export (Save As).
Still TODO: Import settings logic.

Added a Save As and Load button to the bottom of the project settings dialog tree.

![mwsave](https://user-images.githubusercontent.com/1795082/54491440-f4be9080-4894-11e9-976b-dac6cada7f2d.png)

**Comment by isolver** [comment]
Load Settings functionality implemented, but needs some testing and feedback please. 

Changed the settings file name(s) used by MarkWrite, so this version will **not** use previously saved settings from older versions of markwrite and will start with defaults. 

Path for current and default settings files:

C:\Users\USER_NAME\AppData\Local\MarkWrite\MarkWrite

Previously, settings were saved default_settings.pkl. Now, first time markwrite is run, it will create two settings files, initially identical:

- default_settings.pkl
- current_settings.pkl

These 2 file names are reserved in markwrite, i.e. you can not save a settings file yourself with either of these names.

default_settings.pkl is a backup of the applications initial defaults, so a user can select this to revert to original settings.

current_settings.pkl stores the applications current settings and is updated each time markwrite is run.

**Comment by isolver** [comment]
Also note that if you load a settings file, some settings will not take effect until the MarkWrite application is restarted, like graph foreground and background colors and maybe others. There is no way to get around this really.

**Comment by g-no** [comment]
This seems to work. There is are a few more issues here (don't know if this was the case before):

- [ ] Point size for Horizontal Pen Position Trace doesn't have an effect
- [ ] Point size for Velocity Trace doesn't have an effect
- [ ] Point size for Accelleration Position Trace doesn't have an effect

Works after reloading the file, but not immediately.

**Comment by isolver** [comment]
Closing this bug and making #146 a P1 if that is OK.
