### ISSUE TITLE
restore previous version of wintabtest

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#201]
The attempts to integrate MS Surface 3 support resulted in a new version of wintabtest. Please restore the old one without Surface 3 support (the new one doesn't work well with wacom devices).

**Comment by isolver** [comment]
I think the issue might be that the wintab_test.py is just running in the 'mouse simulation' mode we added by default now. 

Try changing line 49 of  wintab_test.py to be:

wintab.WintabTablet':{'name':'tablet', 
                                   'mouse_simulation': **False**,

instead of True. The script should then actually use the wintab driver during the test.

I will also make the default False in the distribution.

**Comment by g-no** [comment]
Yes, that does the trick. Good to make this default.

While testing this I stumbled upon the third value, presented after the X and Y coordinates. It's somehow a negative pressure value that is 0 while the pen is on the tablet and rises up to 1023 when the pen is out of reach. Do we collect this value? If not we should. Made another issue out of this: #206 .
