### ISSUE TITLE
Zooming segment view leaves selected data view blank

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#32]
Zooming the segment view seems to break it quite easily, with no action resulting in redisplay of a segment. e.g., double clicking on segment tag, or creating new segment does not refresh the segment view, which remains blank.

An easy fix for this would just be to prevent manual zooming of segment view. I think it's fine without.

**Comment by isolver** [comment]
On Mon, Apr 13, 2015 at 5:43 PM, Mark-Torrance notifications@github.com
wrote:

> Zooming the segment view

What is the segment view? The Selected Data View, or of the others?
If you mean the Selected Data view, then I agree, we could disable zooming
via the mouse in that view since it is controlled by what is selected.

The bug is easy to fix though, the issue is that I check that the data is
within the view, but I do not check that the zoom level has been manually
adjusted to be too wide, resulting in any selection being < 1 screen pixel.
;)

**Comment by Mark-Torrance** [comment]
Sorry - selected data view. Better (slightly) to keep zooming in if easily fixed, I think.

**Comment by isolver** [comment]
Sometimes the little things are bigger than expected. ;) OK, finally got this working in a sensible way (I think). 

When data is selected, existing Selected Data pan / zoom functionality is unchanged except:
1. Now when the selected data next changes, the Selected Data view auto ranges so that the new selected data is zoomed (with aspect ratio of 1).
2. Also enabled the little 'A' button that appears in the bottom left hand corner of a view when you have changed the pan/zoom with the mouse. If you click the 'A' button, the pan/zoom goes back to what it was when the last data selection change occurred.

**Comment by Mark-Torrance** [comment]
Excellent. (I was wondering why only little A in the Timeline.)
