### ISSUE TITLE
Deleting segment should have no effect on selection or focus

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#42]
Currently deleting an item automatically changes the selection in the timeline to the parent segment, with associated zooming out in timeline and spatial view. This is annoying. Your next selection is typically going to be local to the one that you deleted. Can we have it so that deleting a segment makes not changes to focus or selection?

**Comment by Mark-Torrance** [comment]
@isolver: If this is not a quick thing to fix, please demote to lower priority.

**Comment by isolver** [comment]
Right now there must always be a selection in the segment tree, the top
level category (which internally is a segment itself), is used if there are
no segments.

This brings me to something I have been thinking about over the last few
days, as it would actually solve the issue you raised here.

There is, in a way, an inconsistency in the app because a node in the seg
tree must always be selected  / active, but when you are manually moving
the selection region in the time plot view, the timeplot and spatial views
all reflect what the selection region is, not what the currently active
segment node is. So really the selection region itself be , at least just
on the back end, a stand alone segment class instance, and should become
the 'active segment' in the situation discussed here. It would not show up
in the segment tree, or get output to any reports, it would just make the
overall app functionality much more consistent. This would improve things
because:
- it would deal with this issue, since we could make the 'active segment'
  the selection region.
- It means that when manipulating the selection region, the properties
  table in the lower right hand corner of the app would be updated with info
  on the selection region as it is changed.

What do you think Mark? I think if we are going to change this, it is
better done now, as it will only get harder to change as the app grows in
complexity.

**Comment by Mark-Torrance** [comment]
YES. This makes loads of sense to me. Also makes the program more coherent for future developers.

**Comment by isolver** [comment]
OK then this should be a Priority 1 Initial release change / bug / issue.

**Comment by Mark-Torrance** [comment]
I think this is now superseded by #46. @isolver close?

**Comment by isolver** [comment]
I hope #46 will also directly fix this, but we should keep this open until we know for sure.

I am working on this one now. It is a good thing to make this type of fundamental low level change early. Already it is taking much longer to do than I thought because of all the areas of the code that depended on or made assumptions related to the code design area being changed. 

Once I have it working properly, it will simply the interdependencies between the different data views etc..

**Comment by isolver** [comment]
Fixed
