### ISSUE TITLE
Jumping whole slection forward doesn't work for some timeline locations

### ISSUE THREAD

**Issue by Mark-Torrance** [isolver/OpenHandWrite#60]
Behaviour: I can't identify any specific features of the next sample that might make this happen but (a) if you use ctrl+right to jump the whole sample forwards repeatedly you quite soon come to a situation where it refuses to jump and (b) if you get to one of these sticking points and keep trying to jump the selection after a few actions shrinks to nothing.

I'm thinking that this is partly to do with adding an autotrim action to the jump, which I know we discussed but I can't now see the need for (now that there's a key to move the end of the segment, and this action necessary snaps to non-zero). I'm also thinking that the current action isn't what I thought it was (though probably is what we agreed!). I think that all it needs to do is move the start forward to the first non-zero sample after the current end, and move the end forward the same amount of time (so that duration is maintained).

**Comment by isolver** [comment]
I think the part a) of the issue happens if the selected timeline period
duration < the time to the next pen sample time. The current ctrl+right
action keeps the selection time period duration, so in this case zero
samples would be selected so the action is aborted.

The part b is likely from some part of the code /not/ crhevking that the
new selection time period contains at least 2 samples, so the selection
region start and end times become equal.

I will look into these .
