### ISSUE TITLE
Auto-segmentation (up- and down-strokes)

### ISSUE THREAD

**Issue by g-no** [isolver/OpenHandWrite#94]
Automatic segmentation of strokes (up- and downstrokes) can be either based on
1. inversions in Y-coordinates, or
2. the absolute velocity minimum
The results are more or less identical in a lot of cases. In horizontal lines, like e.g. the stroke of a 't', the Y-coordinates are problematic as lots of strokes can be the result. This issue should be solved by using the absolute velocity.
When I used Y-coordinates in previous scripts, it was much more reliable to draw the segments from the raw data (i.e. not from the smoothed data. I don’t know if this is also true for the absolute velocity.) On TabletPCs with low resolution (pixel) I had the problem of several identical values (samples) in the turning point. In these cases I chose the one with the lowest absolute velocity.

**Comment by isolver** [comment]
Stroke boundary points are found by determining the samples within a period of pen pressed samples that have local minima in the sample's absolute xy velocity. The local minima alg. implementation is basically a python port of the matlab 'findpeaks', function. Currently the alg uses no minimum relative peak high and uses a 10 sample minimum peak to peak distance. If you like how the alg seems to be working, I can bring out these parameters into the application settings so they can be changed to tweak things for the current data file loaded.

**Comment by isolver** [comment]
@g-no, @Mark-Torrance:

So I am making some good progress on adding this. A few questions that maybe you can answer so I can make changes to the code as needed before sending you a version to test.

1) Stroke boundary points are only found for samples that have pressure > 0. That is correct right?

2) Often there will be: 
    a) 1 - n pressed samples at the start of a pressed sample run before the first segment boundary point is found.
    b) 1 - n pressed samples at the end of a pressed sample run after the last segment boundary point is found.

Currently, the samples that fall into a) and b) are not used in reporting a stroke region. Should they be included? i.e. 
     a) For first stroke of a pressed sample run, stroke start should always be the first sample in the pressed sample run?
     b) For last stroke of a pressed sample run, stroke end should always be last sample of the pressed sample run?

 See images strokes1.png - strokes3.png for examples. The red dots are the samples selected as stroke boundaries by the auto detect functionality that is run when the data file is first loaded into the project.
![strokes1](https://cloud.githubusercontent.com/assets/1795082/11824320/046a7536-a347-11e5-9dc2-52d79c4dde42.png)
![strokes2](https://cloud.githubusercontent.com/assets/1795082/11824329/083e25ea-a347-11e5-80a3-4c38ca427945.png)
![strokes3](https://cloud.githubusercontent.com/assets/1795082/11824336/0b7bba60-a347-11e5-9c76-313283008e7e.png)

**Comment by g-no** [comment]
1) If it's possible to expand stroke boundary points for pressure=0 samples with justifiable effort, this would be good to have.

If the answer is no, then:
2a) Stroke start should always be the first sample in the pressed sample run.
2b) Stroke end should always be last sample of the pressed sample run.

If the answer is yes, then stroke start/end will probalbly not apply to samples at the start/end of a pressed sample run, but:
2a) Stroke start should always be the first hover.
2b) Stroke end should always be last sample before OOR.

3) Auto Stroke segmentation doesn't make sense, if the velocity is below a certain threshold for a certain number of samples/ms. I used ot take 1% of the participants maximum velocity as a threshold, but that can only be done offline. As 'normal' local minima in automated movements have a duration of 5-50 ms (roughly estimated), 50 ms of extra low velocitiy seems to be a reasonable span for skipping stroke segmentation.

4) Most of the red dots look reasonalbe, but I don't understand the ones in the middle of the downstroke of the 1 (second red dot) and the 2 (third red dot). What's happening there? They both don't look like velocity minima.

**Comment by Mark-Torrance** [comment]
I'm ignoring this on the grounds the @g-no is the expert (except to say that this looks cool). It that's not ok, let me know.

**Comment by isolver** [comment]
##### Re: stroke detection using pressed sample runs only vs full sample series

@Mark-Torrance you may want to read this one over, as there maybe ab interaction between how strokes are segmented vs. how markwrite by default trims segments created by a user.

> 1) .... possible to expand stroke boundary points for pressure=0 samples 
> with justifiable effort, this would be good to have.

So we would just run the local minima alg across each full pen sample series, instead of running it for each pressed sample run within a series? If the answer is yes, then this is easy to change. If you mean something more complicated, answer TBD. ;)

> If the answer is no, then:
> 2a) Stroke start should always be the first sample in the pressed sample run.
> 2b) Stroke end should always be last sample of the pressed sample run.

Simple enough.

> If the answer is yes, then stroke start/end will probably not apply to samples at the start/end of a 
> pressed sample run, but:
> 2a) Stroke start should always be the first hover.
> 2b) Stroke end should always be last sample before OOR.

So does this mean that it is in effect the same as the 'no' option above, but:
- " first hover" replaces "first sample in the pressed sample run"
- " last sample before OOR" replaces "last pressed sample of the ... run"

If this is correct, then again this would be easy to change. If I an missing some complexity here, then effort TBD. ;)

*Possible issue with including hover samples in strokes: 
- Right now there is a markwrite project setting that determines of hover samples are stripped from the start / end of a segment when it is created. Default is to strip hover samples.
- For stroke segmentation, how does this setting interact?
- Perhaps the setting itself should be used to determine which samples in a series are included:
  - if True, strokes are created based on pressed sample runs only
  - if false, strokes are generated using the full sample series

*Question: If hover samples are included in strokes, does that mean that a stroke could exist where all the samples are hover samples? i.e. strokes could be detected between two pressed sample runs?

##### Re: Adding velocity threshold to stroke detection alg

> 3) Auto Stroke segmentation doesn't make sense, 
> if the velocity is below a certain threshold for a certain number of samples/ms. 

I wonder if this could be handled using the current algorithm by setting a minimum difference threshold between a stroke boundary candidate samples xy_velocity vs the velocity of neighbouring samples. i.e. if a local minima is only accepted if its velocity value is > X units less than surrounding samples.  

Do you think this is worth trying? If so I will try adding a such a threshold and we can see how it works vs. removing stroke boundary candidates that have a xy_velocity < a threshold value.

I think it may also help remove some of the boundary points that are currently being selected 'mid' stroke as you mention in the following point.

##### Mid - stroke boundary points being detected

> 4) Most of the red dots look reasonalbe, but I don't understand the ones in the middle of the 
> downstroke of the 1 (second red dot) and the 2 (third red dot). What's happening there? They both 
> don't look like velocity minima.

I think this maybe because, as mentioned above, there is no threshold in the current detection alg. that states the minimum difference between a boundary candidates xy_velocity vs. the velocity of neighbouring samples. This may cause very small 'peaks' in low accelleration periods to be identified as local minima == stroke boundary.

Will have to look into this more though.

**Comment by Mark-Torrance** [comment]
> >    .... possible to expand stroke boundary points for pressure=0 samples
> >     with justifiable effort, this would be good to have.
> 
> So we would just run the local minima alg across each full pen sample series, instead of running it for each pressed sample run within a series? If the answer is yes, then this is easy to change. If you mean something more complicated, answer TBD. ;)

Currently these are computed when data are read into MW? If so, then yes, just run across all series. Can't see a disadvantage of doing this.

>    If the answer is yes, then stroke start/end will probably not apply to samples at the start/end of a
>     pressed sample run, but:
>     2a) Stroke start should always be the first hover.
>     2b) Stroke end should always be last sample before OOR.

Yes

> So does this mean that it is in effect the same as the 'no' option above, but:
>     " first hover" replaces "first sample in the pressed sample run"
>     " last sample before OOR" replaces "last pressed sample of the ... run"

It would seem so.

> If this is correct, then again this would be easy to change. If I an missing some complexity here, then effort TBD. ;)

I can't see another sensible way of doing this. Stroke (including air-stroke) boundaries are marked in the data as it's read in. It's then up to users how they use these in their segmentation (if at all) and how we / users use them in calculating output variables. I'm seeing loads of potentially interesting stuff to do with this, even for users who are not directly interested in strokes.

> *Possible issue with including hover samples in strokes:
> 
> Right now there is a markwrite project setting that determines of hover samples are stripped from the start / end of a segment when it is created. Default is to strip hover samples.
>     For stroke segmentation, how does this setting interact?
>     Perhaps the setting itself should be used to determine which samples in a series are included:
>         if True, strokes are created based on pressed sample runs only
>         if false, strokes are generated using the full sample series

I don't think that's the right strategy. Stroke boundaries need to be there in the data whatever the segmentation strategy being used.

Step back a moment: more generally, what happens if I try to create a segment that is entirely made up of hover events and hover stripping == true? What should happen is that this segment just can't be created.

I think once that is sorted then the stroke issue is also sorted. If hover stripping, then segment which starts or ends with hover samples gets these trimmed. If not, then it doesn't. If a user is interested in strokes and wants to include hover strokes then they just need to get to set hover stripping == False.

> *Question: If hover samples are included in strokes, does that mean that a stroke could exist where all the samples are hover samples? i.e. strokes could be detected between two pressed sample runs?

Ah, and we are thinking the same way. See above.

> > ###Re: Adding velocity threshold to stroke detection alg###
> > 
> >  3) Auto Stroke segmentation doesn't make sense,
> >     if the velocity is below a certain threshold for a certain number of samples/ms.

A side note - @g-no said in previous notes that it's not possible to work out a by-session (by-subject) minimum velocity. This would be possible by doing some calculations on the data after it's read in and before local minima (stroke boundaries) are calculated. If this is true, I'm not suggesting doing it now but it's perhaps a Phase 3 todo. (by which I mean create new issue and set Milestone to "Future, date unknown").

**Comment by g-no** [comment]
Hmm, not fast enough.

The idea with the project setting would solve the issue. Like you proposed:
- if True, strokes are created based on pressed sample runs only
- if False, strokes are generated using the full sample series
  This includes:
- if True, stroke start/end should always be the first/last sample in the pressed sample run
- if False, "first hover" replaces "first sample in the pressed sample run" and "last sample before OOR" replaces "last pressed sample of the ... run"

Concerning a minimum difference threshold I'm not sure. I'll post a possible solution in an hour or so.

**Comment by g-no** [comment]
Here's an excel sheet with the details. This could be improved, but may be suffcient for the moment.
[Inversions.xlsx](https://github.com/isolver/OpenHandWrite/files/64293/Inversions.xlsx)

**Comment by isolver** [comment]
Closing this general feature request, as it has been implemented. Specific issues / changes regarding stroker detection should be raised as separate openhandwrite issues.
